---
name: akoranga

releases:
- name: akoranga-nginx-boshrelease
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 170.14

instance_groups:
- name: akoranga-nginx
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: nginx
    release: akoranga-nginx-boshrelease
  vm_type: default
  networks:
  - name: default
  stemcell: default
